"""add_data_providers_and_provenance_schema

Revision ID: a38da25dc012
Revises: e9219b1cbd09
Create Date: 2026-09-29 19:53:59.390623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38da25dc012'
down_revision: Union[str, None] = 'e9219b1cbd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agriculture_statistics',
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agriculture_statistics_country'), 'agriculture_statistics', ['country'], unique=False)
    op.create_index(op.f('ix_agriculture_statistics_crop'), 'agriculture_statistics', ['crop'], unique=False)
    op.create_index(op.f('ix_agriculture_statistics_region'), 'agriculture_statistics', ['region'], unique=False)
    op.create_table('data_providers',
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('data_type', sa.String(length=60), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('authentication_type', sa.String(length=50), nullable=False),
    sa.Column('api_version', sa.String(length=30), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('auth_status', sa.String(length=60), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_records',
    sa.Column('observation_type', sa.String(length=60), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('quality_status', sa.String(length=30), nullable=False),
    sa.Column('freshness_status', sa.String(length=30), nullable=False),
    sa.Column('data_age_hours', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_records_observation_id'), 'data_quality_records', ['observation_id'], unique=False)
    op.create_table('provider_sync_runs',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_sync_runs_provider_id'), 'provider_sync_runs', ['provider_id'], unique=False)
    op.create_table('data_conflicts',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('provider_a_id', sa.UUID(), nullable=True),
    sa.Column('value_a', sa.String(length=200), nullable=False),
    sa.Column('provider_b_id', sa.UUID(), nullable=True),
    sa.Column('value_b', sa.String(length=200), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_conflicts_farm_id'), 'data_conflicts', ['farm_id'], unique=False)
    op.create_table('farm_data_snapshots',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_version', sa.String(length=40), nullable=False),
    sa.Column('weather_snapshot', sa.JSON(), nullable=False),
    sa.Column('soil_snapshot', sa.JSON(), nullable=False),
    sa.Column('satellite_snapshot', sa.JSON(), nullable=False),
    sa.Column('water_snapshot', sa.JSON(), nullable=False),
    sa.Column('crop_snapshot', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('source_attributions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_data_snapshots_farm_id'), 'farm_data_snapshots', ['farm_id'], unique=False)
    op.create_table('raw_observations',
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('source_dataset', sa.String(length=100), nullable=False),
    sa.Column('external_record_id', sa.String(length=200), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('data_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_observations_external_record_id'), 'raw_observations', ['external_record_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_farm_id'), 'raw_observations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_provider_id'), 'raw_observations', ['provider_id'], unique=False)
    op.create_table('sync_events',
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_farm_id'), 'sync_events', ['farm_id'], unique=False)
    op.create_table('water_observations',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('moisture_source_type', sa.String(length=50), nullable=False),
    sa.Column('irrigation_applied_mm', sa.Float(), nullable=True),
    sa.Column('drought_index', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('quality_status', sa.String(length=30), nullable=False),
    sa.Column('freshness_status', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_observations_farm_id'), 'water_observations', ['farm_id'], unique=False)
    op.alter_column('farm_risk_scores', 'farm_health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('satellite_observations', sa.Column('freshness_status', sa.String(length=30), server_default="unknown", nullable=False))
    op.add_column('satellite_observations', sa.Column('quality_status', sa.String(length=30), server_default="good", nullable=False))
    op.add_column('satellite_observations', sa.Column('external_id', sa.String(length=150), nullable=True))
    op.add_column('satellite_observations', sa.Column('ingested_at', sa.Date(), nullable=True))
    op.add_column('soil_observations', sa.Column('electrical_conductivity', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('sulfur', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('zinc', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('iron', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('copper', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('manganese', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('boron', sa.Float(), nullable=True))
    op.add_column('soil_observations', sa.Column('freshness_status', sa.String(length=30), server_default="unknown", nullable=False))
    op.add_column('soil_observations', sa.Column('quality_status', sa.String(length=30), server_default="good", nullable=False))
    op.add_column('soil_observations', sa.Column('external_id', sa.String(length=150), nullable=True))
    op.add_column('soil_observations', sa.Column('ingested_at', sa.Date(), nullable=True))
    op.add_column('weather_observations', sa.Column('freshness_status', sa.String(length=30), server_default="unknown", nullable=False))
    op.add_column('weather_observations', sa.Column('quality_status', sa.String(length=30), server_default="good", nullable=False))
    op.add_column('weather_observations', sa.Column('external_id', sa.String(length=150), nullable=True))
    op.add_column('weather_observations', sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observations', 'ingested_at')
    op.drop_column('weather_observations', 'external_id')
    op.drop_column('weather_observations', 'quality_status')
    op.drop_column('weather_observations', 'freshness_status')
    op.drop_column('soil_observations', 'ingested_at')
    op.drop_column('soil_observations', 'external_id')
    op.drop_column('soil_observations', 'quality_status')
    op.drop_column('soil_observations', 'freshness_status')
    op.drop_column('soil_observations', 'boron')
    op.drop_column('soil_observations', 'manganese')
    op.drop_column('soil_observations', 'copper')
    op.drop_column('soil_observations', 'iron')
    op.drop_column('soil_observations', 'zinc')
    op.drop_column('soil_observations', 'sulfur')
    op.drop_column('soil_observations', 'electrical_conductivity')
    op.drop_column('satellite_observations', 'ingested_at')
    op.drop_column('satellite_observations', 'external_id')
    op.drop_column('satellite_observations', 'quality_status')
    op.drop_column('satellite_observations', 'freshness_status')
    op.alter_column('farm_risk_scores', 'farm_health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_water_observations_farm_id'), table_name='water_observations')
    op.drop_table('water_observations')
    op.drop_index(op.f('ix_sync_events_farm_id'), table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_raw_observations_provider_id'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_farm_id'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_external_record_id'), table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index(op.f('ix_farm_data_snapshots_farm_id'), table_name='farm_data_snapshots')
    op.drop_table('farm_data_snapshots')
    op.drop_index(op.f('ix_data_conflicts_farm_id'), table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index(op.f('ix_provider_sync_runs_provider_id'), table_name='provider_sync_runs')
    op.drop_table('provider_sync_runs')
    op.drop_index(op.f('ix_data_quality_records_observation_id'), table_name='data_quality_records')
    op.drop_table('data_quality_records')
    op.drop_table('data_providers')
    op.drop_index(op.f('ix_agriculture_statistics_region'), table_name='agriculture_statistics')
    op.drop_index(op.f('ix_agriculture_statistics_crop'), table_name='agriculture_statistics')
    op.drop_index(op.f('ix_agriculture_statistics_country'), table_name='agriculture_statistics')
    op.drop_table('agriculture_statistics')
    # ### end Alembic commands ###
