"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { Advisory } from "@/lib/types";
import { AdvisoryCard } from "@/components/AdvisoryCard";
import { EmptyState } from "@/components/EmptyState";
import { CardSkeleton } from "@/components/LoadingSkeleton";
import { titleCase } from "@/lib/format";

export default function AdvisoriesPage() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const { data, isLoading } = useQuery({
    queryKey: ["all-advisories"],
    queryFn: () => api.get<Advisory[]>("/api/v1/advisories"),
  });

  const canReview = user?.role === "agronomist" || user?.role === "platform_admin";

  const review = async (id: string, approve: boolean) => {
    await api.post(`/api/v1/advisories/${id}/review?approve=${approve}`);
    queryClient.invalidateQueries({ queryKey: ["all-advisories"] });
  };

  return (
    <div className="mx-auto max-w-4xl space-y-5">
      <div>
        <h1 className="text-page-title text-text-primary">Advisories</h1>
        <p className="text-sm text-text-secondary">
          Structured, evidence-backed recommendations generated by BHOOMI&apos;s deterministic agriculture engine.
        </p>
      </div>

      {isLoading && <CardSkeleton />}
      {!isLoading && (!data || data.length === 0) && <EmptyState title="No advisories yet" description="Advisories appear here once farm intelligence has been computed." />}

      <div className="space-y-3">
        {data?.map((a) => (
          <div key={a.id}>
            <AdvisoryCard advisory={a} />
            {canReview && a.review_status === "pending" && (
              <div className="mt-1 flex items-center gap-2 rounded-b-card border border-t-0 border-border bg-background px-4 py-2">
                <span className="text-xs text-text-muted">Pending agronomist review</span>
                <button onClick={() => review(a.id, true)} className="ml-auto rounded-md border border-border px-3 py-1 text-xs font-medium text-success hover:bg-primary-soft">
                  Approve
                </button>
                <button onClick={() => review(a.id, false)} className="rounded-md border border-border px-3 py-1 text-xs font-medium text-danger hover:bg-red-50">
                  Reject
                </button>
              </div>
            )}
            {a.review_status !== "pending" && (
              <p className="mt-1 px-1 text-[11px] text-text-muted">Review status: {titleCase(a.review_status)}</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
